//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarefa_Testes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefas
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Data { get; set; }
        public int Id_usuario { get; set; }
        public int Id_estadotarefa { get; set; }
    
        public virtual StatusTarefa StatusTarefa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
